airbnb:
  outputs:
    dev:
      type: snowflake

      account: unbrlpp-nh98616

      user: dbt

      role: TRANSFORM

      database: AIRBNB
      schema: DEV
      warehouse: COMPUTE_WH

      threads: 1

      private_key_path: /workspaces/course/airbnb/rsa_key.p8

  target: dev
